spring.application.name=gym-management-service

spring.profiles.active=local

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

management.metrics.tags.application=${spring.application.name}

management.prometheus.metrics.export.enabled=true