spring.application.name=gym-management-service

spring.profiles.active=local

server.port=${SERVER_PORT:8080}

eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

management.metrics.tags.application=${spring.application.name}

management.prometheus.metrics.export.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
workload.queue=${WORKLOAD_QUEUE:trainer.workload.queue}