
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:gymdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:gym}
spring.datasource.password=${DB_PASSWORD:gym}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never

spring.h2.console.enabled=false

logging.level.com.gym=INFO
cors.allowed-origins=*

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
